### ISSUE TITLE
Add a way to easily set up a development environment

### ISSUE THREAD

**Issue by heiglandreas** [opencfp/opencfp#1084]
Currently as a new contributor I need to setup a complete dev-environment to get everything up and running. 

But it would be much easier and faster (and perhaps even more reliable) when I could fire up a dev-environment with a command such as `docker-compose up` or `vagrant up` and start developing right away.

**Comment by mdwheele** [comment]
@heiglandreas

This is what I currently use for development: https://github.com/mdwheele/opencfp-docker

I would be glad for someone else to give it a test drive and kick the tires. It's something I would be interested in adding to the project some day. We've talked about doing so in the past. There are instructions for setting it up as-if it were part of the project so that when integrated there will be minor changes for folks that happen to have worked with it already. 

Let me know what you think.

**Comment by mdwheele** [comment]
Worth noting that you have to get your development config right. This is something that I would document if it were integrated here. I apologize if I'm making a lower assumption of knowledge. All Docker Compose services should be addressable by name, so the host for database is "db", etc.

**Comment by heiglandreas** [comment]
Hey @mdwheele : Do I get that right that I need to clone opencfp-docker insight opencfp? 

Like this?
```php
git clone git@github.com:[user]/opencfp.git
cd opencfp
git clone https://github.com/mdwheele/opencfp-docker.git
cd opencfp-docker
cfp up
```

**Comment by mdwheele** [comment]
That's right. I would rename the directory to ".docker" and also add it to ".git/info/exclude" in your clone of OpenCFP. Check out the README in the Docker repository. I'm on phone and might have typod

**Comment by mdwheele** [comment]
Whoops! I thought I had added instructions re: lining. I have another project similar to run GitHub Classroom.  It can be adapted for this: https://github.com/mdwheele/classroom-docker/blob/master/README.md

Really, it's just about getting a .docker directory into root of your OpenCFP repo and ignoring it without committing to .gitignore. 

Sorry for confusion.

**Comment by heiglandreas** [comment]
No Problem :) Got it running (hopefully, it's still running `cfp build`)

**Comment by mdwheele** [comment]
Yeah, if we ever pull it in here, I plan to get Travis to build it and push to Docker Hub so you don't have to wait on build. Luckily it's more or less a one time thing to get some tools and extensions on the image.

**Comment by llbbl** [comment]
I tried dockerizing it last year with Alpine linux as base and definitely didn't work, or at least without a lot more work into the Dockerfile, because of lack of SMTP support in the container and inability to use API based Mail delivery in the app. 

Good job @mdwheele on getting this working with php7.1-fpm as your base. Let me know if you need help with your repo? :)

**Comment by llbbl** [comment]
@heiglandreas I use Laravel Valet with a Custom Driver. I suppose I should get it added to the Wiki here for other people in similar situation.  I am not sure they will approve my PRs to the valet repo for this.

**Comment by linuxjuggler** [comment]
@heiglandreas check the updated [readme](https://github.com/opencfp/opencfp/blob/master/README.md#build-docker-image) file and [docker.md](https://github.com/opencfp/opencfp/blob/master/DOCKER.md) file, which includes information about how to build your own docker image and how to use this image for development.

Also, the [readme](https://github.com/opencfp/opencfp/blob/master/README.md#using-vagrant) file now includes information about using Laravel homestead for an easy development setup
