### ISSUE TITLE
Allow users to view their submissions after CFP has ended

### ISSUE THREAD

**Issue by tobiasgies** [opencfp/opencfp#153]
As someone who has submitted talk proposals, I'd like to be able to view my talk proposals after the CFP has ended. Currently, all I get is an error message telling me that I can't edit my talks after the CFP has ended. I'd like it if the "edit" link were replaced by a "view" link after the end of the CFP, so I can still see what exactly I submitted.

I'm willing to implement that feature myself and send you a pull request when I'm done. I created this ticket to make sure I don't forget the idea. I'd also like to know if anyone else would like to see this feature or if I'm the only one.

**Comment by coudenysj** [comment]
+1 @tobiasgies need any help with this?

**Comment by tobiasgies** [comment]
@coudenysj I'm currently quite short on time. I stand by my intention to implement this feature, but don't know when I'll be able to get to it yet. If you'd like to take over, feel free.

**Comment by mdwheele** [comment]
@coudenysj @tobiasgies Could you two take a look at #183 when you get a second? The capability to view a talk after CFP has ended is now implemented. I wanted to make sure what was done was actually what you were expecting because, for the most part, it seemed to already be done.

Current master shows an "Edit" button that, when clicked, shows a flash message of "Blah blah after CFP", but otherwise shows the talk information.  I've updated this to replace "Edit" with "View" as suggested, but otherwise took this as an opportunity to refactor another use-case into the service layer.

Thoughts?

**Comment by coudenysj** [comment]
Thanks @mdwheele. Are you sure the current master shows the information after clicking the edit button?

The problem was not that the label was wrong, but that we could not access the talk information after the CFP has ended.

Looking at your screenshots, I see that problem is resolved, so thank you very much!

**Comment by mdwheele** [comment]
@chartjes this can probably be closed unless there's anything else.
