### ISSUE TITLE
Error complaining about missing group during user signup

### ISSUE THREAD

**Issue by chartjes** [opencfp/opencfp#179]
Vance Lucas reported that he is getting an error
http://cl.ly/Zw3P

**Comment by chartjes** [comment]
A test is required for the signup controller to duplicate the problem.

**Comment by mdwheele** [comment]
This is covered end-to-end [here](https://github.com/opencfp/opencfp/blob/master/tests/functional/visitor/registers-as-speaker.feature#L13-L17).  I am able to reproduce locally by dropping the `Speakers` role from the `groups` table. We can write something up that would mock that "suddenly becoming unavailable", but that seems like a pretty deep problem. If the database just started getting thrashed about, how would we *want* to react?

Could it be that the system's database was not migrated to current version or could this be a CFP instance that was old-enough that it was migrated before a bunch changes were made there? We moved a base schema SQL dump into a first-migration on the 10/24/14.

https://github.com/opencfp/opencfp/blob/master/migrations/0_schema.php#L17-L29

**Comment by chartjes** [comment]
Vance said he ran the migrations. I am wondering if I should try creating a brand-new VM and run the migrations on it

**Comment by mdwheele** [comment]
That's an idea. I've dropped my database and re-ran migrations a few times and everything is peachy until I remove the `Speakers` role. Same error. I also can't find anywhere that would provide allowance for mutation of that in source either. 

Could we verify that his database has both required groups from the migration? If it does, then it's very curious that Sentry cannot find the group. I'd be looking over there at that point.

**Comment by vlucas** [comment]
The situation is weird. I did run the migrations, and I do have the necessary groups in the database: http://cl.ly/ZvDh

I am still investigating as well. This error is happening both locally and on the CFP instance I setup on my VPS.

**Comment by vlucas** [comment]
I went through the setup process again and discovered the issue was a database DSN that is structured differently than the provided one in the sample config files. There are no errors about the DSN string format or parsing it, etc. so that's why this error is so weird.

Format Expected: `mysql:dbname=cfp_tp;host=127.0.0.1`
Format Given (that does not work): `mysql://root@localhost/cfp_tp`

What tripped me up is that the given format is the standard DSN string format, while the expected one is not. Everything worked once I gave it the DB credentials in the same format as the example DSN string.

**Comment by mdwheele** [comment]
Yeah... that's pretty annoying. My understanding is that the PDO MySQL connector does not allow credentials to be passed according to the standard [DSN format](http://en.wikipedia.org/wiki/Data_source_name). I bet there's *some* level of sanity checking we could do for stuff like this though if it would be valuable. Odd that PDO itself doesn't barf on it.

Other than that, sorry for the troubles!

Reference:

- [DSN Format](http://en.wikipedia.org/wiki/Data_source_name)
- [StackOverflow: Why is PHP PDO DSN a Different Format for MySQL vs Postgres](http://stackoverflow.com/questions/237367/why-is-php-pdo-dsn-a-different-format-for-mysql-versus-postgresql)

**Comment by mdwheele** [comment]
Heh... so... while it's good that the work in #182 is done so that there is some pre-flight for PDO's service provider; I was doing some other work on the project and remembered that both [Sentry](https://github.com/opencfp/opencfp/blob/master/classes/OpenCFP/Provider/SentryServiceProvider.php#L18-L26) and [Spot](https://github.com/opencfp/opencfp/blob/master/classes/OpenCFP/Provider/SpotServiceProvider.php#L16-L31) are not using the DSN configuration setting. In addition, that string really *is* meant to be what goes into the PDO constructor as "$dsn". So, there's some room for improvement in clarity.

That said, as long as you make sure to provide valid credentials in the other configuration options, then PDO, Sentry, and Spot should function as expected. 

I'll submit a follow-up to clean that up... I can see where that's going to cause some confusion for folks.
