### ISSUE TITLE
API to allow remote submissions

### ISSUE THREAD

**Issue by chartjes** [opencfp/opencfp#191]
Create an API to allow users with valid accounts submit talks via 3rd party software

**Comment by mdwheele** [comment]
@chartjes do you know if anybody has taken up this work other than the commits you've put down on #174? It's probably a good candidate for cross-project work at tek between OpenCFP and [Symposium](https://github.com/tightenco/symposium). Anywho, I've got time to put down on building this out. I just wanted to get some thoughts from you on a few stories before getting started.

**Comment by chartjes** [comment]
Nobody has done anything else about it. I should just delete the PR and think of a more robust solution

**Comment by mdwheele** [comment]
I'll put some thoughts together and want to take a swing, if you're amenable. If you'd rather take it on yourself, that's cool too! :smile:

**Comment by chartjes** [comment]
I would rather that the damn thing get done, don't care who does it.

--
Chris Hartjes chartjes@littlehart.net



On Mon, May 11, 2015, at 10:01 AM, Dustin Wheeler wrote:
> I'll put some thoughts together and want to take a swing, if
> you're amenable. If you'd rather take it on yourself, that's cool
> too! :smile:


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/opencfp/opencfp/issues/191#issuecomment-100917607

**Comment by mdwheele** [comment]
Roger.

**Comment by mdwheele** [comment]
Will be sending a documentation PR drafting usage and configuration of API tomorrow evening. This will be ahead of an implementation following shortly after. I've got most of the plumbing done on this and am just plugging implementations in at this point. Hopefully, we can discuss more next week in-person, make adjustments and :shipit: Was able to consolidate a lot of stuff into the service layer and refactor existing TalkController to use it. Tests are green, but I'll likely be refactoring some of the test suite to clean up the amount of mock-chain we have to do. Since they're "controllers as services" now, that should be a lot cleaner.

**Comment by mdwheele** [comment]
Implemented in #197
