### ISSUE TITLE
Adding code style/quality tools

### ISSUE THREAD

**Issue by yitznewton** [opencfp/opencfp#234]
I propose we add style and quality tools to the Travis build, which would both communicate the project's code requirements to developers automatically, and alleviate the need for reviewers to comment on style violations. My recommendations:

* http://phpmd.org/
* https://github.com/FriendsOfPHP/PHP-CS-Fixer

I'll be happy to set those up

**Comment by yitznewton** [comment]
There's also codesniffer; at my last PHP shop we used all three of these. I'm not sure what PHP_CS adds over phpmd

**Comment by mdwheele** [comment]
PHP_CodeSniffer detects violations of specified code style. PHP-CS-Fixer simply builds on top of that to auto-fix those violations for you. Not sure if it would ever make sense to run both since PHPCSF covers that entire use-case (identification (through `--dry-run`) of violations as well as fixing). PHPMD isn't as much concerned with code-style as it is an attempt at static analysis of code. It's going to look for duplication of code. It's going to look at method cyclomatic complexity. Etc. It will also probably light up like Las Vegas when pointed at OpenCFP so it might feel odd for **someone** submitting a [simple fix](https://github.com/opencfp/opencfp/pull/233) to get notes about completely unrelated code "being inefficient". Food for thought. Maybe we just want to introduce code-style checks for now?

In addition, we also have (a not well publicized) Codeclimate registration at https://codeclimate.com/github/opencfp/opencfp that I think is really a better solution for the job. Rather, it's already covering the case of "inefficient code" etc etc. Through configuration, I believe we can get it to report status changes on PRs as a check as well. We mentioned something similar to them at php[tek] this year, but I lost track of where that went.

Questions for consideration:

* Will we have PHP CS Fixer doing dry-runs detecting code style violations or will we be somehow configuring it to actually make changes + commits to PRs. FWIW I think I'd prefer the former; having it simply communicate the violation.
* Will we have PR merges **require** that these code-style tests pass or do we make it less strict than that. 
* Rather than hitting every PR with `phpmd` what if we better publicized the Codeclimate registration and pointed folks there as a "low hanging fruit" or opportunity to contribute. We could also better track that over time. 

Take nothing above as assertive / conclusive. I'm in a rush and was just getting some ideas out! Definitely open for discussion.

**Comment by yitznewton** [comment]
I'm not a fan of autocorrect in the background; I was trying out the tools on a different codebase, and it did break some things.

My suggestion would be, set up CS-Fixer for dry run to break Travis, assuming there's not major blockers as far as fixing existing issues in the code as it is today.

I'll try a branch and see what that looks like

**Comment by localheinz** [comment]
@yitznewton 

:+1: for `php-cs-fixer`! Also comes with possibility to cache between builds, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/master!

**Comment by localheinz** [comment]
@yitznewton 

Also cool: provide a `Makefile` with a `cs` target, so you can run the fixer locally, too!

**Comment by yitznewton** [comment]
Heh @localheinz, where have I seen that before :wink:

**Comment by localheinz** [comment]
@yitznewton 

Maybe here: https://github.com/zendframework/modules.zendframework.com/blob/master/.travis.yml?

Hehe.

**Comment by yitznewton** [comment]
Mwahaha https://github.com/easybiblabs/oauth2-client-php/blob/master/Makefile#L14-L16

**Comment by localheinz** [comment]
@yitznewton 

Till added it for GetCourse! Great idea back then.

**Comment by localheinz** [comment]
@yitznewton 

Turns out, though, that I was the one originally adding `phpcs` and `phpmd` for `getcourse/api` - code was in a mess back then.

**Comment by chartjes** [comment]
Looks like it's resolved
