### ISSUE TITLE
/admin/speakers and /admin/admins are visible to anonymous users

### ISSUE THREAD

**Issue by davethegr8** [opencfp/opencfp#385]
# Steps required to reproduce the problem

1. not be logged in
2. go to one of those urls
3. see stuff

# Expected Result

* This should not happen

# Actual Result

* It happens

**Comment by pmeth** [comment]
yowza!!

**Comment by mdwheele** [comment]
Sigh. I hate that trait with a passion for exactly this reason haha. Visibility on those methods was recently changed to public, which killed the magic method on AdminAccessTrait that sets up __call. 

Can be fixed by demoting visibility OR by manually checking OR at routing layer. I'm away from a terminal at the moment and can't fix this but if I see nothing when I get back tonight, I'll send a patch.

**Comment by mdwheele** [comment]
See 3d46f38

**Comment by davethegr8** [comment]
I did a quick patch on cascadiajs that seemed to fix the issue: https://github.com/cascadiajs/opencfp/commit/4245d4f00beeb6c3facac4dc1b99ff1faf53c0aa

Probably not ideal, but it seems to work.
