### ISSUE TITLE
Exception occurs when running migrations on MySQL 5.7.12

### ISSUE THREAD

**Issue by ramsey** [opencfp/opencfp#395]
# Steps required to reproduce the problem
1. Set up a new database user and an empty database
2. Configure database settings in phinx.yml and config/production.yml
3. Run `vendor/bin/phinx migrate --environment=production`
# Expected Result
- Migrations succeed with no errors.
# Actual Result
- PDOException thrown when migrating `20150702132854_fix_defaults_for_users_table.php`:

```
[PDOException]
SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'activated_at'
```

It seems this might be the case because the value "0000-00-00 00:00:00" is not valid when `NO_ZERO_DATE` is enabled, and as of MySQL 5.7.8, it is enabled by default. See http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_zero_date

Setting the following in `my.cnf` fixes the problem, but I'm worried that my server mode is not strict enough now:

```
[mysqld]
sql_mode = 
```

**Comment by mdwheele** [comment]
Thanks @ramsey. Related to this issue is https://github.com/opencfp/opencfp/blob/master/migrations/20160106061843_fix_zero_dates.php which was put in place to fix this exact issue for servers that had the users table (and more) and did an I place upgrade of MySQL. 

We can likely apply a similar fix up to the offending migration or (might actually be a better solution) set the SQL mode less permissive at runtime in order to get through the migrations (allowing the current existing one to do its job). SQL mode should not persist past the session required to do migrations but if it does we can revert to original configured value. 

Thoughts anyone else?

**Comment by chartjes** [comment]
I'm in favour of any solution that does not require users to alter their mysqld settings...

**Comment by chartjes** [comment]
There are no longer any migrations that set dates to 0000-00-00 00:00:00 so I am closing this issue.
