### ISSUE TITLE
Allow users to submit "Joint" talks

### ISSUE THREAD

**Issue by llbbl** [opencfp/opencfp#400]
### Current Behavior

Not supported
### Suggested Enhancement

Allow people to add other users if they know their username to their submitted talk. Update admin page to display multiple speakers.

**Comment by mdwheele** [comment]
Awesome! I have some questions and some random notes for future.

- Will the join users have to exist previously? If not, do we send them an invite and "attach" them after their registration is successful?
- Requiring the speaker to know either an email address or username is probably acceptable. *Autocompleting is probably not a good idea because it'd allow someone to scan for speakers that have submitted*
- Do both users "own" the talk? If I invite you to speak jointly on "Test Driven Speaking", are you able to delete that talk? What about update the description?

Good idea! I'm going to think a little more on UX and come back. It'll be a little awkward to implement, maybe, but that's honestly an opportunity to refactor a bit to make the change easier :)

Thanks!

**Comment by llbbl** [comment]
_- Will the join users have to exist previously? If not, do we send them an invite and "attach" them after their registration is successful?_

Yea I think so. We can assume they know each other outside of the site and can communicate what each of their usernames are via some other channel. 

_- Requiring the speaker to know either an email address or username is probably acceptable. Autocompleting is probably not a good idea because it'd allow someone to scan for speakers that have submitted_

Email or username would work. Autocomplete is a bad idea, yea. Ideally we would send the second person an email confirmation before they are added fully and the talk is "accepted". If the user doesn't exist yet let them submit form and just keep the talk in a "pending" status. (if that isn't too much trouble). Open to alternative ways to solve this problem. 

_- Do both users "own" the talk? If I invite you to speak jointly on "Test Driven Speaking", are you able to delete that talk? What about update the description?_

Person who submitted owns it. If joint speakers change it is up to the OP to fix the talk. 


Expanding on the Join talk feature: 
We should build it to support Panels, were we would need the ability to have more than just two speakers. Maybe CSV separated or something easy would work for initial version?

**Comment by mdwheele** [comment]
> We should build it to support Panels, were we would need the ability to have more than just two speakers. Maybe CSV separated or something easy would work for initial version?

Yeah, we would plan on doing more than a single joint speaker I think. Zero, one or many! 😄 

> Ideally we would send the second person an email confirmation before they are added fully and the talk is "accepted". If the user doesn't exist yet let them submit form and just keep the talk in a "pending" status. (if that isn't too much trouble). Open to alternative ways to solve this problem.

I don't know if it's so much a requirement that all the joint speakers sign on before the talk can be considered. I do think having suggested join speakers confirm is important, otherwise there is room for abuse. I feel like if the talk owner submits a talk and says "here are some other joint speakers", it might still be considered by a selection committee, but we should show clearly that "2/3 joint speakers have confirmed" so that appropriate planning can be done around travel / lodging. Maybe this is configurable by the administrator; `consider_pending_joint_talks`.

Good stuff.

**Comment by localheinz** [comment]
I think this is a good idea!
