### ISSUE TITLE
Use PSR–11 implementation instead of Pimple

### ISSUE THREAD

**Issue by localheinz** [opencfp/opencfp#723]
In order to move forward with #618, we should probably use a [PSR–11](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-11-container.md) implementation (rather than Pimple).

**Comment by mdwheele** [comment]
I think the next step for the references issue is to decide on framework and just start moving. It looks like Symfony 4 is going to win. 

I don't think swapping an alternative container is necessary to make progress. I also think this is a great opportunity to do the great "controllers as service" migration if we're continuing to endeavor for unit tests as the framework layer. It'll help to have dependencies injected rather than passing around the container. 

FWIW: Pimple does "support" PSR 11. See https://github.com/silexphp/Pimple/blob/master/README.rst#the-psr-11-container-class. But even with that convenience, probably better to make a clean break for 2.0 to Symfony 4 (or whatever framework)

Personally, I would really really like to get to the point where framework doesn't matter and build a solid service layer. But time is the enemy for me at the moment. In that model, we could really focus on tests for OUR code and write looser integration / e2e tests for things dealing with HTTP (routing / controllers)

My 2c

**Comment by mdwheele** [comment]
I've started the migration to Symfony 4. Using this as an opportunity to eradicate Controller reliance on direct-access to container; instead relying on Symfony's service DI. Current strategy is manually moving code from this code-base to the new (which began as a fresh Symfony 4 Flex install). 

There are some migration details I want to help ease, but the goal is to get a solid-enough baseline / pattern established for moving code and publish that on a branch here so we can all start chipping in. It would just be too hectic to have everybody "go at it" right now.

Closing this, but feel free to re-open. Just grooming.

**Comment by BackEndTea** [comment]
@mdwheele Just gonna say this here, but if this breaks BC, maybe start the migrations from scratch as well? 
As in start over with a base migration which makes the DB as we want it now.
