### ISSUE TITLE
RFC: New submission and merging process for PR's

### ISSUE THREAD

**Issue by chartjes** [opencfp/opencfp#762]
I have a weird desire to get all these PR's merged as soon as possible so I am not being as thorough as I could be, so I want to propose some new ground rules for managing the submission and merging of PR's.

I want every PR to have a review request attached to it. I will not merge any PR's that did not have a review request and will not merge any PR's that have not passed a review.

Sometimes I have to put things in front of me to slow me down.

**Comment by BackEndTea** [comment]
Sounds good to me, maybe this will stop me from introducing bugs all over the place

**Comment by localheinz** [comment]
@chartjes 

Problem is that contributors other than maintainers cannot request a review! 🤓

**Comment by chartjes** [comment]
@localheinz Is there a setting I can change to allow non-maintainers to request a review?

**Comment by localheinz** [comment]
@chartjes 

I don't think so, that's only possible for collaborators!

**Comment by chartjes** [comment]
Okay, I added in @localheinz and @BackEndTea as collaborators

**Comment by localheinz** [comment]
@chartjes 

Nice, thank you!

You should probably enforce an approved pull request review in https://github.com/opencfp/opencfp/settings/branches/master!

**Comment by chartjes** [comment]
@localheinz Done -- all PR's should require a review now. I don't think I should turn on "require review from Code Owners" because not everyone who has written code still contributes to the project

**Comment by localheinz** [comment]
@chartjes 

One more question, though, how would you prefer to go forward with merging PRs?

Once approved, who can or should merge the PR?

**Comment by BackEndTea** [comment]
@chartjes Thanks for the collaborator role.

**Comment by BackEndTea** [comment]
@chartjes 

Do you want to enforce something along the lines of 'A PR larger than X requires multiple reviewers'?

**Comment by mdwheele** [comment]
> Do you want to enforce something along the lines of 'A PR larger than X requires multiple reviewers'?

I think we should use our best judgement rather than enforcing much of anything. If someone sends a 1 line diff (I'm looking at you @localheinz with all your check PRs :grin:), then that's pretty straight forward. I guess it's a good example too (e.g. @localheinz sends a check that might be "controversial". He's pretty good about recognizing that and asking for additional scrutiny. Maybe that wouldn't be a PR I would just merge without further conversation other than a "Thanks!"). 

If someone sends 3000 lines that crosses multiple boundaries of abstraction, it's probably best for the reviewer to reach out to another reviewer OR for the contributor to even realize what they've done :skull:  and apologetically ask for additional review. 

All in all, I think the four of us can be responsible open-sourcers. :smile:

**Comment by localheinz** [comment]
@BackEndTea @chartjes @mdwheele 

Regarding https://github.com/opencfp/opencfp/issues/762#issuecomment-347574917, can we clarify?

For example, if I open a PR, someone else approves it, who should be allowed to merge it?

**Comment by chartjes** [comment]
I would go with method 1 -- the reviewer merges it in, which is what I have been doing here

**Comment by mdwheele** [comment]
I think we've come to a decent resolution. Feel free to re-open; just grooming.
