### ISSUE TITLE
Discussion: What to do with the test suite?

### ISSUE THREAD

**Issue by BackEndTea** [opencfp/opencfp#927]
Some related issues/PRs/discussions are:
* #919
* #917
* #774
* #721

Our current coverage, (including integration tests,) looks like this:
![image](https://user-images.githubusercontent.com/14289961/34038010-11107c84-e18b-11e7-8e1b-fcdf1a4e21a4.png)

And from #917 we found that our mutation metrics are as follows:
```
Metrics:
     Mutation Score Indicator (MSI): 77%
     Mutation Code Coverage: 85%
     Covered Code MSI: 90%
```
Looking at this, i'd like to think we are doing pretty well, as far as our test suite goes. We covered roughly 87% of all code lines, and 90% of all mutations in the covered lines were caught by our tests.
See [infections explanation](https://infection.github.io/guide/#Metrics-Mutation-Score-Indicator-MSI) about the metrics to see exactly what they mean.

But when i look at the readme of the project, i see 36% coverage, which makes it look like there are a whole lot less tests then there actually are.

The discussion in #919 showed that we have a lot of different ideas on how to close the difference between what our 'badges' say, and what our coverage is.

Some of the options are:
* Rewrite integration tests to be unit tests
* Collect coverage from integraton tests, but with ```@covers``` annotation
* A mix of the two. To quote @mdwheele  
* >  I think we should do that and follow-up by identifying poor integration tests and deciding "Is this actually better as a Unit test? Or is this an actual integration and we need to hit database / sessions to test it."

No matter which option we go for, i'm still in favor of #774. In that we should have e2e tests, in a framework that was designed for e2e tests, like behat.

Lastly, i found that the html coverage from phpunit gives really great insight in where the issues and risks lie. I would like to suggest maybe hosting that in the github pages of this project, or making a separate project in the opencfp organisation which holds that.

cc: @chartjes @mdwheele @localheinz

**Comment by mdwheele** [comment]
@BackEndTea thanks for writing this up.

> Some of the options are:
> * A mix of the two. To quote @mdwheele

I'm obviously a fan of this option :grin:. I think that in the short-term it offers the best benefit ensuring we have coverage over the things we're targeting via explicit `@covers` annotations while also allowing us to begin refactoring parts of our test suite. 

> Lastly, i found that the html coverage from phpunit gives really great insight in where the issues and risks lie. I would like to suggest maybe hosting that in the github pages of this project, or making a separate project in the opencfp organisation which holds that.

This is a great idea. We should do this. We could have TravisCI push coverage results to `gh-pages` here.

> No matter which option we go for, i'm still in favor of #774. In that we should have e2e tests, in a framework that was designed for e2e tests, like behat.

I'm about to send a PR with our first passing Behat feature :grinning: 

```bash
mdwheele@4e0238d2ceb8:/usr/src/app$ vendor/bin/behat 
Feature: Homepage

  Scenario: It loads!           # tests/Features/homepage.feature:3
    Given I am on the homepage  # OpenCFP\Test\Features\Contexts\FeatureContext::iAmOnHomepage()
    Then I should see "OpenCFP" # OpenCFP\Test\Features\Contexts\FeatureContext::assertPageContainsText()

1 scenario (1 passed)
2 steps (2 passed)
0m1.28s (9.57Mb)
```

**Comment by chartjes** [comment]
@BackEndTea Also, thanks for starting this discussion. You did highlight something that really bothers me:

* including integration tests we have an awesome code coverage value of 87%
* if we use just the unit tests we have a less-than-awesome code coverage value of 36%

So I think I would be comfortable doing the following

* Remove the badges because they are sending conflicting messages
* Publish the coverage stuff to GitHub Pages so people can see what's going on and generate it once we switch to train releases in the new year
* Start looking at the integration tests and see how many of them can become unit tests
* Once we've moved to Symfony 4 integration + Behat tests will be a lot quicker due to their use of the Kernel http://symfony.com/doc/current/testing.html

**Comment by derrabus** [comment]
> Once we've moved to Symfony 4 integration + Behat tests will be a lot quicker due to their use of the Kernel http://symfony.com/doc/current/testing.html

If you're referring to the functional tests outlined in http://symfony.com/doc/current/testing.html: You can write those already. Silex offers a compatible test client and with #934 we've integrated it into our `WebTestCase` class.

**Comment by chartjes** [comment]
This is what I am referring to

https://twitter.com/samuelroze/status/941010870464806914

**Comment by mdwheele** [comment]
> https://twitter.com/samuelroze/status/941010870464806914

Yep! And for the tests that require JavaScript interaction, you can set tags (`@javascript`) to execute against a headless-browser. Ends up working out really nice.

**Comment by BackEndTea** [comment]
Should we replace the controller/action 'integration' tests with the behat tests from #1018 ? Or do we keep both alongside each other?

cc @chartjes @mdwheele @localheinz

**Comment by mdwheele** [comment]
I think the Behat suite should represent critical paths only. It should represent the "core `Features`" of OpenCFP and scenarios that govern their operation. I think `Integration` should represent our technical integration of domain to particular infrastructure (e.g. `AccountManagement` to `Sentinel`, `Authentication` to `Sentinel`, etc.). Because we are treating our controllers as command handlers / use-cases of the application, it makes sense to `Unit` test them, but in a lot of code-bases, I don't bother because the controllers are driving a service layer or putting things on a command-bus. Not much value there.

So I think:

1. Critical path features are represented in the Behat suite. There should be relatively few of these and they are *not* comprehensive. For instance, I would *not* test every way a web-form can fail with BDD features. Make that a `Unit` test for the controller (or even better, actually `Unit` test the domain).
1. `Integration` tests are very targeted and focus-mostly on things in the `Infrastructure` namespace. That namespace is where we "tie ourselves to the metal" and they deserve tests that actually exercise that rope.
1. `Unit` tests become the bulk of our overall suite. Tests for controllers / actions? Probably should be Unit tests unless there is some technical blocker in the short-term (and even then, that should be cause for creation of an issue to resolve).

**Comment by BackEndTea** [comment]
>So I think I would be comfortable doing the following
> * Remove the badges because they are sending conflicting messages
> * Publish the coverage stuff to GitHub Pages so people can see what's going on and generate it once we switch to train releases in the new year.

@chartjes Do we still want to do this?

**Comment by chartjes** [comment]
@BackEndTea Yes I would like to do this. Because we are only tracking code coverage for unit tests the number is totally misleading. I have no idea how to send the coverage stuff to GitHub pages so someone will have to set that up

**Comment by BackEndTea** [comment]
I personally don't like having a gh-pages folder in *this* repo, or a gh-pages branch.

Its probably best to create a repo dedicated to the gh pages and send the coverage report there.
