### ISSUE TITLE
RFC: interactive set-up

### ISSUE THREAD

**Issue by BackEndTea** [opencfp/opencfp#999]
Currently, when trying to set OpenCFP up for production, i found there were a lot of small things that needed changing.

So i'm proposing some kind of interactive set-up. I was thinking something among the lines of a shell script that asks you things like the hex of the brand color you wish to use, the uploads location for the profile images you wish to use, and all those things.

Which also brings me to the next point. Some things are defined in multiple places, like the logo, which is hard coded in the views multiple times. In order for this interactive set-up to be possible, most of these would have to be defined in one place, so it can be edited with a script.

**Comment by chartjes** [comment]
I think this would be great -- we will need something like this if we ever want to create images that will run up on Heroku (I think)

**Comment by BackEndTea** [comment]
Its not *needed* but it makes everything a whole lot easier. Because right now its just a big hassle to change the same thing in 10 different files

**Comment by mdwheele** [comment]
Hahahahahah, @BackEndTea! I'm so glad to see someone else post this. I've been dabbling with a web-based installer for OpenCFP but stopped working on it because of all the recent churn. I had limited time and rebasing *constantly* was getting in the way of progress. I'd be down to send that sooner or later. It's fairly similar to the "WordPress 5-minute Install". Basically just need to get dependencies installed and then it takes off. Can set up logo, splash, talk topics, types, etc.
